Rails:
  Enabled: true
Documentation:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
