version: '2'

services:

  website:
    depends_on:
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    volumes:
      - 'redis:/var/lib/redis/data'

volumes:
  redis:
