version: '2'

services:

  website:
    build: .
    command: puma -C config/puma.rb
    depends_on:
      - 'redis'
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'

  tests:
    build: .
    command: bundle exec rspec
    volumes:
      - '.:/usr/src/app'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

volumes:
  redis:
