default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: postgres

development:
  <<: *default
  database: free-send-mails-api_development

test:
  <<: *default
  database: free-send-mails-api_test

production:
  <<: *default
  database: free-send-mails-api_production
